#requires built images:
#from this directory run:
#docker build -t img-tt-dashboard .

#run docker compose:
#docker-compose -f docker-compose.yml up

#access to bash on tt-dashboard service:
#docker exec -it tt-dashboard bash

#using envionment variables like:
#export TT_DASHBOARD_CODE=~/dev/tracktruckprojects/tt-dashboard
#export TT_DASHBOARD_IMAGE=img-tt-dashboard:latest

version: '3'
services:
  tt-dashboard:
    image: ${TT_DASHBOARD_IMAGE}
    container_name: tt-dashboard-cont
    ports:
      - "80:4200"
    volumes:
      - ${TT_DASHBOARD_CODE}:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules
    labels:
      kompose.service.type: LoadBalancer
    working_dir: /usr/share/nginx/html
